### ISSUE TITLE
phase raising openhtf.util.measurements.InvalidType

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#104]
openhtf.util.measurements.InvalidType: Invalid measurement type: [Measurement(name='current_1', units=None, outcome=None, docstring=None, dimensions=None, validators=[]), Measurement(name='current_2', units=None, outcome=None, docstring=None, dimensions=None, validators=[]), Measurement(name='current_3', units=None, outcome=None, docstring=None, dimensions=None, validators=[])]

Trying to declare measurements with a loop:

@names.measures([names.Measurement('current_%s' % i) for i in ['1','2','3']])

**Comment by fahhem** [comment]
Try this:

`@names.measures(*(names.Measurement('current_%s' % i) for i in ['1','2','3']))`

That creates an iterator and converts it into arguments

**Comment by wallacbe** [comment]
That worked, thank you


Brandon Wallace | Test Engineer | wallaceb@google.com <lapetina@google.com>
*v**erily*

**Comment by fahhem** [comment]
Did this work?

**Comment by wallacbe** [comment]
Worked, closing issue
