### ISSUE TITLE
PhaseExecutor and PlugManager should not be mutablerecords.Record subclasses

### ISSUE THREAD

**Issue by grybmadsci** [google/openhtf#106]
Executor and Manager obviously imply more functionality than a POD type.  I think we should discourage using records for anything but POD types (potentially with minimal additional convenience functionality).  

Using mutablerecords outside of POD types translates to "we don't like the way Python classes work, so we redid it", and I think that's frustratingly obfuscated for any outside developers looking at the code.

That said, I think this is super low priority and more of an aesthetic change.

**Comment by fahhem** [comment]
This seems done at HEAD
