### ISSUE TITLE
Update of readme needed

### ISSUE THREAD

**Issue by didjado** [google/openhtf#1199]
it seam that the examples section of the readme i needing updating as it mentions the setup.py file that doesn't exist or is now missing

it would also be help full to mention which versions of python defiantly work with examples and i cannot get any of them to work

I was using spintop version of  openhtf and that was easy to get going and i have just been bashing my head against the wall trying to get examples working as they all have issues with python 3.9 3.10 and 3.13

**Comment by glados-verma** [comment]
The supported versions of Python can be seen in `pyproject.toml` - see `requires-python`.

I'll update the docs that still refer to setup.py, thanks for calling that out.
