### ISSUE TITLE
Support outputting attachments as separate files in JSON output module

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#140]
Using JSON output module with binary output file raises:
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 0: invalid start byte

Propose we skip attachments for this module or skip the encoding and just save binary file?

**Comment by grybmadsci** [comment]
There's an option to skip attachments already, pass inline_attachments=False when you create the OutputToJSON object.

That said, we really need to fix this for real - we should check the MIME type, and anything but plaintext should get uuencoded when we serialize.  We might also consider putting a size limit (or at least a warning when you go over a certain size) to avoid gigantic json files blown up even larger with huge uuencoded binary data that should really just get spit out in a standalone file.

**Comment by grybmadsci** [comment]
Can't assign @fahhem for some reason, but he's poking around at similar things and might fix this along the way.. otherwise I'll do it eventually :)

**Comment by glados-verma** [comment]
Please reopen if still applicable.
