### ISSUE TITLE
add config values to default output modules for added traceablity

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#141]
add config values to default output modules for added traceablity

**Comment by grybmadsci** [comment]
you could do this manually pretty easily by doing config=conf.Config().dictionary in the constructor of the Test object, and it would show up in metadata.

what are everyone's thoughts on doing this vs. implicitly adding config to metadata vs. creating a 'config' top level key in the test record and putting it there?  any of these are fairly easy to do.

**Comment by wallacbe** [comment]
+1 implicitly add to metadata

**Comment by wallacbe** [comment]
Looks like config=conf.Config().dictionary is no longer supported.  Should I add a GetDictionary method to Configuration class?

**Comment by grybmadsci** [comment]
nope, use `conf._asdict()`, already done for you ;)

**Comment by wallacbe** [comment]
Thanks that worked.  Any qualms about accessing private attribute, should I change to public?

**Comment by grybmadsci** [comment]
nope, it's not actually private, it's underscored to avoid name collision (config attributes can't start with underscore for that reason).  we also established a convention internally that `_asdict()` is used to provide serialization-friendly dictionaries of things, so it's consistent with that.
