### ISSUE TITLE
Console logs inconsistent with test_record logs (console missing lines)

### ISSUE THREAD

**Issue by grybmadsci** [google/openhtf#142]
I've got a few test phases, and for some reason calling test.logger.info(...) isn't producing console logs until partway through the test, when they start appearing.  All log lines are in the output test_record, so i'm guessing it's something to do with log levels to console not being set up correctly?  i'll look into it more later and see if i can't figure out what's triggering the change, might lead to the cause of the problem.

**Comment by amyxchen** [comment]
test.logger only log openhtf framework info, not user test info. to setup console log, use flag '--verbosity LEVEL'. LEVEL is one of ['debug', 'info', 'warning', 'error', 'critical'], default is 'warning'], default is 'warning'

**Comment by amyxchen** [comment]
test.logger only log openhtf framework info, not user test info. to setup console log, use flag '--verbosity LEVEL'. LEVEL is one of ['debug', 'info', 'warning', 'error', 'critical'], default is 'warning'.

**Comment by grybmadsci** [comment]
hm, right, but that wouldn't explain why some logs are showing up and some
are not.

**Comment by jettisonjoe** [comment]
This is fixed with the recent logging refactor.
