### ISSUE TITLE
Add green/red text for Pass//Fail Status in CLI

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#147]
Add green/red text for Pass//Fail Status in CLI.  Allows us to see test result better if front end isn't running

**Comment by amyxchen** [comment]
I am on this.

**Comment by jettisonjoe** [comment]
For reference, the plan we talked about was to implement CLI test results as another output module you can optionally add to your tests. Does that sound reasonable?

**Comment by grybmadsci** [comment]
Hm, yeah sounds pretty reasonable, but depending on how much you plan to make it look pretty, this is actually a giant can of worms... even something as seemingly innocuous as red/green text is actually not only OS-specific, but terminal-type specific.  You might consider using a library like ncurses to help, but it'll still be very tough to make truly cross platform and friendly.

**Comment by jettisonjoe** [comment]
Agreed cross-platform colorization is going to be a can of worms for sure. I was thinking CLI test results are important enough that we should try to put something out there with best-effort colorization and refine it later.

**Comment by wallacbe** [comment]
colorama 0.3.7 may be an option here.
Cross-platform colored terminal text.

**Comment by wallacbe** [comment]
Output module exists for this.  Colorama tracked in https://github.com/google/openhtf/issues/300
