### ISSUE TITLE
Add unit tests!

### ISSUE THREAD

**Issue by jettisonjoe** [google/openhtf#15]

**Comment by wallacbe** [comment]
Also include unit test example for phases in hello_world tester

**Comment by wallacbe** [comment]
I'm trying to implement a unit test on a phase.  I'm able to mock the decorators but unsure how to mock   config = conf.Config() with it being global

**Comment by fahhem** [comment]
Just mock it out and then end the mocking when you're done. There are a few ways to do this, we can discuss over chat if you wish

**Comment by wallacbe** [comment]
Looking for unit test example of how we test for a FAIL case of a phase where a measurement is out of Range().  Would we be able to this on a phase level or would we have to do it on a tester level?

**Comment by glados-verma** [comment]
Closing this because some unit tests were added :joy: More seriously though, we can always improve unit test coverage, and intend to track this with coverage tools.
