### ISSUE TITLE
remove stackedconfig, we don't need it now that we don't have providers/capabilities

### ISSUE THREAD

**Issue by grybmadsci** [google/openhtf#165]

**Comment by fahhem** [comment]
I'd say that the conf module can be significantly cleaned up to be a single Config class without a ConfigModel, etc.

**Comment by grybmadsci** [comment]
Agreed, and I hope to address some of @wallacbe 's requests for more convenient default behaviors in some cases.

**Comment by grybmadsci** [comment]
Fix coming in #171
