### ISSUE TITLE
Add more examples that each demonstrate one thing clearly

### ISSUE THREAD

**Issue by grybmadsci** [google/openhtf#166]
Right now we only have the one example that attempts to demonstrate all the things and is getting a bit out of hand.

No assignee, this should really be a team effort, feel free to add some examples.

**Comment by jettisonjoe** [comment]
Some things we need examples of:
- [ ] Defining a  fixture (plug that combines other plugs).
- [ ] Various output modules.
- [ ] Various start and stop triggers.
- [ ] Using phases from a shared phase library.
- [ ] Measurements in all their forms.

**Comment by glados-verma** [comment]
Closing; I'm in favor of #44
