### ISSUE TITLE
Test.Execute() can only be called from the main thread

### ISSUE THREAD

**Issue by grybmadsci** [google/openhtf#192]
```
...
  File "c:\users\cameralab02\git\automation\tbtech\tests\mtf.py", line 280, in _RunTest
    test.Execute()
  File "C:\Users\CameraLab02\venv\lib\site-packages\openhtf\__init__.py", line 125, in Execute
    StopOnSigInt([server.Stop, executor.Stop])
  File "C:\Users\CameraLab02\venv\lib\site-packages\openhtf\__init__.py", line 274, in StopOnSigInt
    signal.signal(signal.SIGINT, _Handler)
ValueError: signal only works in main thread
```
Due to the way my GUI is set up, I have to start the test from not the main thread (Tk similarly throws a hissy fit if you try to relegate it to anything less than the main thread).  I don't think there's any particular reason to force the user to call `.Execute()` from the main thread.

Perhaps we could set up this handler in `.Initialize()` that @fahhem is implementing, and enforce that *that* gets called from the main thread?

As a side note, I plan to get off Tk and use a different GUI mechanism, so long term this won't be a problem for me (and short term I'm just going to comment out that handler).  Nevertheless, seems worth a gander.

**Comment by jettisonjoe** [comment]
I think `.Initialize()` is a _great_ place to set up the signal handling.
