### ISSUE TITLE
Replace python-gflags with argparse

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#205]
Use standard python flags so additional import isn't required.

**Comment by jettisonjoe** [comment]
PR #187 promises to address this.

**Comment by wallacbe** [comment]
Saw a few other places like http_api.py that also use gflags

**Comment by jettisonjoe** [comment]
Yeah, I believe @fahhem is planning to convert everything, pending decisions/solutions for the weirder cases.

**Comment by fahhem** [comment]
Should be fixed, but for some reason I can't even mark this as closed, despite being assigned?

**Comment by grybmadsci** [comment]
Closed!
