### ISSUE TITLE
Gracefully handle network disconnects.

### ISSUE THREAD

**Issue by agdeepak** [google/openhtf#222]
Local Front-end throws network is unreachable error when there is no network connected or the network drops while running front end. This causes front end to crash and it needs to be restarted again or wait until network is connected. 

Issue can be easily reproduced by disconnecting any wifi or ethernet network and then starting front-end locally.
Please see error screenshot attached.
![frontendnetworkunreachableerror](https://cloud.githubusercontent.com/assets/16326136/14469507/d27548e8-0099-11e6-9921-3069c1c763cf.png)

**Comment by jettisonjoe** [comment]
I'll look into fixing this.

**Comment by jettisonjoe** [comment]
Closing this as obsolete because there's a whole new different frontend now!
