### ISSUE TITLE
Front-end IP conflict when 2 LAN networks are connected

### ISSUE THREAD

**Issue by agdeepak** [google/openhtf#223]
(Sighting)
Use case (steps to reproduce):
Connect lab ethernet network on LAN port
Connect another device like USB hub using USB via ethernet adapter
Start Front-end. Error shows IP conflicts as 2 different IPs are assigned for each connected network.

Impact: Unable to run front end when ethernet and USB hub via ethernet connected simultaneously.
Will update the bug with the screenshot during next testing phase.

**Comment by jettisonjoe** [comment]
Screenshot or console copy/paste would be helpful.

**Comment by jettisonjoe** [comment]
I have two network interfaces I can set up on my machine. I will attempt to repro.

**Comment by grybmadsci** [comment]
I suspect this requires the ability to bind any ports we listen on to a specific interface (via `conf` seems reasonable).  I've already built this into the new up-and-coming `station_api`, you'll need to do something similar in the frontend backend (lol) @jettisonjoe .

**Comment by jettisonjoe** [comment]
We might want to check on multicast, too, although I think I wrote that to explicitly listen on _all_ interfaces.

**Comment by jettisonjoe** [comment]
Confirmed tornado-based frontend now listens on all interfaces by default. Starting the frontend with two networks connected no longer produces an error.
