### ISSUE TITLE
ENGR vs PROD output data

### ISSUE THREAD

**Issue by agdeepak** [google/openhtf#225]
Request for a flag or option to distinguish between ENGR and PROD runs in OpenHTF.

**Comment by fahhem** [comment]
You can include this as a 'measurement' or in the metadata. I don't think OpenHTF should include this since there are so many different ways to interpret this and many teams want to do it differently

**Comment by agdeepak** [comment]
This feature is basically required for end-to-end testing and data uploading setup. The data upload doesn't care about measurements pass/fail and since all PROD and ENGR data gets uploaded from the same local folder to remote, it becomes hard to distinguish between fake and real unit data records with actual DUT IDs. Metadata option might work but server will need to parse it during test record upload.

**Comment by fahhem** [comment]
Wherever it goes, the server will need to parse it somehow. You can decide to make it a flag and have it go in the filename that gets created, or it can come in from a prompt and go into a measurement, but that's entirely up to you.

**Comment by agdeepak** [comment]
Ok, let me explore this option offline and I will get back on this issue. I will mark it closed if it gets resolved by enabling this in measurement or a flag option.

**Comment by wallacbe** [comment]
How about embedding prod vs eng into the serial number?

**Comment by jettisonjoe** [comment]
I believe this came up before when we were talking about data collection and my advice then was to use an entry in the 'metadata' field in the test record. Our data team might have even already verbally agreed that they could parse it from there.

**Comment by agdeepak** [comment]
That is correct, Joe. We did talk about this but I wanted to add this issue here to track it until closure and to explore any other alternate solutions (like above proposed solutions). I can followup on metadata or measurements field options and close the issue once we have a solution in place.

**Comment by jettisonjoe** [comment]
@agdeepak, any progress on this issue? Have you been able to take advantage test metadata to differentiate test run types?

**Comment by jettisonjoe** [comment]
As of now the recommended fix is to use test metadata. Marking closed.
