### ISSUE TITLE
Display print statements or logs in front-end

### ISSUE THREAD

**Issue by agdeepak** [google/openhtf#226]
Current front end shows Display Prompts for the user inputs and Phase statuses. Requesting for a feature to redirect some print or log statements from the console to the front end for user to see the test execution progress, status and/or exceptions thrown during test run.

**Comment by jettisonjoe** [comment]
The new frontend will display any log entries that are captured in the test record.

As a side note, test scripts generally shouldn't use print statements except for debug purposes during development.

**Comment by jettisonjoe** [comment]
Logs are now displayed in the web frontend via #246. Closing.
