### ISSUE TITLE
Measurements results in frontend at end of test

### ISSUE THREAD

**Issue by agdeepak** [google/openhtf#227]
Openhtf frontend shows 'UNSET' instead of actual measurements during test execution and PASS/FAIL test result at the test stop. Requesting for a feature in Front-end to display the actual measurements with Pass/Fail or atleast the Fail measurements results at the end of test.

Impact:
User needs to check for the pass/fail measurements in the terminal console or json outputs.

**Comment by jettisonjoe** [comment]
This is because pass/fail evaluation currently happens at the end of a phase rather than at the time the measurement is set. The PR that adds the frontend will address this.

**Comment by jettisonjoe** [comment]
This should be fixed now!
