### ISSUE TITLE
Clean up phase interfaces

### ISSUE THREAD

**Issue by grybmadsci** [google/openhtf#244]
This includes the phase data object passed into phases, and the return value from phases, (`PhaseResult.FAIL` should really be `PhaseResult.STOP` to match `PhaseResult.CONTINUE` and `PhaseResult.REPEAT`).

I'd like to know if anyone is actually using `PhaseResult` values to return from Phases, @wallacbe @fahhem @jettisonjoe ?

**Comment by fahhem** [comment]
I have a REPEAT and a FAIL use already, but I'm able to update them as necessary
when I import the openhtf changes, so I'm fine with a STOP. However, would STOP
set the outcome to FAIL or ABORTED or a new STOPPED?





On Mon, May 9, 2016 3:39 PM, grybmadsci notifications@github.com wrote:
This includes the phase data object passed into phases, and the return value
from phases, ( PhaseResult.FAIL should really be PhaseResult.STOP to match PhaseResult.CONTINUE and PhaseResult.REPEAT ).

I'd like to know if anyone is actually using PhaseResult values to return from Phases, @wallacbe @fahhem @jettisonjoe ?

**Comment by wallacbe** [comment]
I'm not using the PhaseResult values

**Comment by jettisonjoe** [comment]
I don't think anyone in Aura is using them.

**Comment by glados-verma** [comment]
Some work has been done to `PhaseResult`; it's a bit cleaner now. I know we use it in my group.
