### ISSUE TITLE
Make OpenHTF truly cross-platform.

### ISSUE THREAD

**Issue by jettisonjoe** [google/openhtf#26]
Right now we're using a modules that are *nix-specific in a couple of places. Notably 'inotify' and 'select'. Users can currently work around this using VMs, but we should try to work natively on Linux, OSX, and Windows if possible.

**Comment by wallacbe** [comment]
I'm seeing cases with V1.0 where CTL+C doesn't always stop the process and I have to kill it.

**Comment by jettisonjoe** [comment]
wallaceb, see #14 where SIGINT handling bug is being tracked.

**Comment by jettisonjoe** [comment]
I think all three major platforms have been tested and work at this point, so closing.
