### ISSUE TITLE
Tab completion breaks when usb_plugs extra excluded.

### ISSUE THREAD

**Issue by jettisonjoe** [google/openhtf#339]
I saw a weird error and I'd like to look into it at some point. I think it's an oh-my-zsh thing (https://github.com/robbyrussell/oh-my-zsh/pull/3373) so not a huge priority. I don't think Bash even tab completes Python modules.

``` bash
~/src/openhtf/examples» python -m opERROR:root:Failed to import M2Crypto, did you pip install openhtf[usb_plugs]?    ±
ERROR:root:Failed to import M2Crypto, did you pip install openhtf[usb_plugs]?
```

**Comment by glados-verma** [comment]
Closing as stale.
