### ISSUE TITLE
Improve DUT result indication in Front End

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#352]
I setup hello_world to loop.  I ran from head and observed that station history isn't enabled yet (I'm assuming this will go on the side of the page.)   When I enter a DUT ID I see the status go to PASS/GREEN, then go to WAITING/GRAY.  I'm unsure if this is adequate for the operator to know a device's result.  Will they need to look at the history once this is available?  Can we keep the last run DUT's  result at the top of the page until we scan the next DUT?

**Comment by jettisonjoe** [comment]
@grybmadsci and I are working on default history in the frontend along with the station API changes, as history depends on the new station API.

**Comment by fahhem** [comment]
I believe if you scroll down (or click on History in the future) you'll see previous results now
