### ISSUE TITLE
Add ability to update dut_id after test start.

### ISSUE THREAD

**Issue by jettisonjoe** [google/openhtf#37]

**Comment by grybmadsci** [comment]
This can already be done by modifying `test.test_record.dut_id`, which is a bit roundabout, but I don't think it's a thing we want people doing all that often?  I can add a `dut_id` property with getter/setter on `PhaseData` that just wraps the same on `test_record` for more direct access?

**Comment by jettisonjoe** [comment]
The current roundabout way works for me. We definitely don't want to encourage widespread use of this mechanism.

**Comment by jettisonjoe** [comment]
Should we revisit this now that we're leaning towards start triggers being full-on phases?

**Comment by jettisonjoe** [comment]
This is done!
