### ISSUE TITLE
Log a warning on setting a measurement to 'None'.

### ISSUE THREAD

**Issue by jettisonjoe** [google/openhtf#4]
This might indicate an 'ERROR' outcome in some scenarios. For instance, if we set a measurement using the output of some hardware plug. Logging a warning in this scenario gives us a breadcrumb in case we don't validate the measurement in this way.

**Comment by grybmadsci** [comment]
Hm, I would contend that we should disallow this entirely.  None is a python-specific thing, and while the framework is in Python, I think we've tried pretty hard to make the test result record language agnostic.  I think setting a measurement to None should raise.

**Comment by fahhem** [comment]
I would consider setting to None the same as being cleared, so it would be an ERROR in the end in the current scheme. How about that?

**Comment by jettisonjoe** [comment]
I think even if we support 'clearing' of measurements with `None`, we still probably want to at _least_ log a warning when doing so.

**Comment by wallacbe** [comment]
Please close
