### ISSUE TITLE
display prompts intermittently don't show up

### ISSUE THREAD

**Issue by rinehartm** [google/openhtf#435]
I am using openHTF v0.9 on ubuntu 16.04.  

The program (written by @grybmadsci ) has several locations where prompts are supposed to appear, but intermittently do not (can be mixed for a given test run: some appear, some do not).  But if valid inputs are supplied, the program proceeds without issue, no warnings or errors.  All prompts are calls to DisplayPrompt().

@grybmadsci suggests this is an openHTF issue rather than specific to our code that runs on top.  He also suggested that more recent versions of openHTF might solve this issue but are not backwards compatible.  

Any ideas on what might be causing these intermittent drops of prompts?

**Comment by jettisonjoe** [comment]
Hit me up internally. Happy to help you convert over to the newer test authoring API where all new bugfixes and features are going.
