### ISSUE TITLE
have execute() return overall outcome

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#449]
I have a script containing who Test objects (Test A and Test B).  I would only like to continue to Test B if Test A is successful.  Can we add feature where execute() returns the overall outcome?

**Comment by jettisonjoe** [comment]
Yes! In fact, #443 includes a commit that does this by making execute() return a boolean where True represents a PASS and False represents a FAIL.

**Comment by fahhem** [comment]
Fixed by #443
