### ISSUE TITLE
Add a "network_silent" or "local_only" flag.

### ISSUE THREAD

**Issue by jettisonjoe** [google/openhtf#463]
Right now it's a little tricky to disable network activity completely, since you need to set both the `enable_station_discovery` command-line flag to `False`, as well as set the `station_api_port` config value to `None` (really `null` if you're doing it via a config .yaml file). It would be a lot more friendly to provide a single flag to turn off all network activity from OpenHTF.

**Comment by fahhem** [comment]
It would also be good to make the test and frontend communicate over
localhost only by default, so you can either enable network discovery or
disable all network activity from there

**Comment by glados-verma** [comment]
Closing as stale, this has not been requested recently.
