### ISSUE TITLE
Pending/upcoming phases are missing from the frontend

### ISSUE THREAD

**Issue by Kenadia** [google/openhtf#468]
Example:

![screen shot 2016-11-29 at 5 25 18 pm](https://cloud.githubusercontent.com/assets/3301218/20736075/1816adb8-b659-11e6-850f-960f88464933.png)

We expect to see a pending phase “hello_world” underneath “trigger_phase”.

**Comment by fahhem** [comment]
I looked into this, it seems to be that the `TestRecord` only has completed phases in it. I'm going to see if we can pre-populate it with all the phases and replace the relevant one or if we have to do something else (like a separate list of pending phases, which was 0.9's approach)

**Comment by fahhem** [comment]
The `StationApi` has been updated to have the test descriptor's phases available. Is that sufficient?
