### ISSUE TITLE
Update documentation and examples/measurement.py

### ISSUE THREAD

**Issue by csaint00** [google/openhtf#470]
Ran into some issues on a fresh install from the documentation. I needed to add the package libprotobuf-dev to the apt-get install line in CONTRIBUTING.md to get protobufs to build and got an error when trying to run the example measurements.py that units could not be found, resolved by importing openhtf.utils.units

**Comment by csaint00** [comment]
Also ran into a problem cloning the git repo, had to use git clone https://github.com/google/openhtf

**Comment by jettisonjoe** [comment]
Oops! Thanks for filing this!

**Comment by jettisonjoe** [comment]
Can you elaborate on the cloning issue, though?

**Comment by csaint00** [comment]
using "git clone git@github.com:google/openhtf.git" errored out with:

git clone git@github.com:google/openhtf.git
Cloning into 'openhtf'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jettisonjoe** [comment]
I _think_ that's an issue with _your_ ssh keys rather than an issue with our repository specifically. Are you able to clone other repo's using ssh? It may just be a matter of generating an ssh key and adding it to your GitHub profile if you haven't yet:

https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by csaint00** [comment]
Fair enough, I'm more of a hardware guy than software guy so not surprised I'm the problem haha

**Comment by fahhem** [comment]
Made the requested changes in #473, let us know how your testing goes!
