### ISSUE TITLE
Start Test Prompt is timing out and raising PromptUnansweredError

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#50]
Start Test Prompt appears to be using same timeout as user prompts.  When using this in loop mode we shouldn't have a timeout

**Comment by jettisonjoe** [comment]
Hmm, good point. I'll wire up a way for the test start trigger to override the global prompt timeout.

**Comment by jettisonjoe** [comment]
Amy is working on this now. The plan we discussed:
  * Add a timeout_s= keyword arg to DisplayPrompt with a default taken from FLAGS.
  * Change the _cond.wait() call to use the new kwarg.
  * In PromptForTestStart, provide an exceedingly long timeout via the timeout_ms kwarg.
