### ISSUE TITLE
Need OutputToTestRunProto to set specifc permissions

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#517]
I need the output of OutputToTestRunProto to have rw set to group, currently only set to user.  Any objections if I default this to group and user by default?

**Comment by fahhem** [comment]
Can you wrap or subclass OutputToTestRunProto and do that there? The permissions are set by the umask, which you can also modify. It's 0027 for me (group gets only read and execute by default), but if you run "umask 0007" then user and group get the same permissions.
