### ISSUE TITLE
StationApi tracks tests based on (hostport, test.uid) combo, but that's not unique enough

### ISSUE THREAD

**Issue by fahhem** [google/openhtf#521]
If a test is run in multiple threads in the same binary, or even multiple times in a row, this causes problems as caches/dicts get filled with the first test seen with that uid. Later, when another test is seen with the same uid, it's assumed the `TestWatcher` will watch it, but it doesn't necessarily and the frontend can freeze.

**Comment by jettisonjoe** [comment]
The station API is no more.
