### ISSUE TITLE
UserInput subclass doesn't display prompts in frontend

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#548]
I'm trying to create a UserInput plug subclass and add new methods:
class OperatorPlug(user_input.UserInput)

However I do not see the prompts displayed in the frontend when i use this.  It works however in CLI

**Comment by fahhem** [comment]
The frontend triggers based on a plug whose path is
'openhtf.plugs.user_input.UserInput', so if you subclass the path is
something else so the frontend would need to be updated to trigger on that
new path
