### ISSUE TITLE
frontend doesn't auto scroll to next test run

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#549]
frontend doesn't auto scroll to next test run.  Have to manually scroll to get to see the trigger phase

**Comment by fahhem** [comment]
The builtin frontend isn't receiving much attention at the moment. Until a
solution is created for supporting multiple teams with the same frontend,
you'll be better off forking it and adding any Javascript or html necessary
to make it work for you. In our case, for instance, we added a plug for
cancelling tests that wouldn't make it into openhtf as it is, but we need
it the way it is
