### ISSUE TITLE
append_record() in history.py adding test time

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#559]
history call back is causing lag.  Pinpointed issue in append_record() 

Added prints in append_record():
1492674275.94 before line 135
1492674275.94 before line 136
1492674279.13 before line 137:
1492674282.73 after line 137

Options proposed in email discussion
drop all_tests_history,
Update total_size() memory size estimates
serialize to disk

**Comment by glados-verma** [comment]
Stale; I couldn't find a `history.py` or `append_record`.
