### ISSUE TITLE
PyPI Release

### ISSUE THREAD

**Issue by jettisonjoe** [google/openhtf#606]
Seems like a while since we've cut a PyPI release. I move to suggest we cut one soon.

**Comment by DanLipsitt** [comment]
Now that 1.1.0 is out, this would be appreciated.

**Comment by fahhem** [comment]
Putting 1.1.0 out was supposed to create the PyPI release :) With #612 in, I re-released v1.1.0 to what is now master: https://pypi.python.org/pypi/openhtf
