### ISSUE TITLE
Have unrun phases show up in test record

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#628]
Feature Request
Have unrun phases show up in test record.  Have measurements and outcomes be UNSET.  Gives output callbacks and frontend added flexibility

**Comment by fahhem** [comment]
Would the phase's outcome be SKIP here, or a new one like NOT_RUN? The frontend should have access to the test descriptor, which has all the phases. For output callbacks, you could get your test descriptor from `test.descriptor` and use that. There are UUID's attached to each phase to be able to detect which ones ran and which didn't. Is that a good enough answer?

**Comment by wallacbe** [comment]
NOT_RUN sounds like a good idea.  For my output callback I'm inheriting from OutputToFile and I only see test_record, which doesn't contain all phases if tester exited early due to an ERROR

**Comment by fahhem** [comment]
You could override `__init__` and take in the descriptor there.

**Comment by wallacbe** [comment]
That approach worked and phases/measurements in the descriptor were in the same order as the test record.

**Comment by fahhem** [comment]
Sounds like it's acceptable? Closing the issue then

**Comment by wallacbe** [comment]
Ya, acceptable, thanks
