### ISSUE TITLE
The equals() validator doesn't accept booleans.

### ISSUE THREAD

**Issue by DanLipsitt** [google/openhtf#642]
Because `validators.equals` delegates to the range validator which calls `isnan`, it causes an exception. This is unexpected behavior, especially since strings are accepted.

**Comment by fahhem** [comment]
How are you constructing a bool that doesn't handle `isnan`?

```py
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
>>> import math
>>> math.isnan(True)
False
>>> math.isnan(False)
False
```
Do you see something else?

**Comment by DanLipsitt** [comment]
That's a real good question! I don't know what was happening and I can't reproduce it now.
