### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#670]
Add support for Python 3

**Comment by wallacbe** [comment]
protobuf==2.6.1 has some Python 3 syntax issues like:
/lib/python3.4/site-packages/google/protobuf/internal/decoder.py", line 488
except UnicodeDecodeError, e:
SyntaxError: invalid syntax

What is motivation behind being on protobuf==2.6.1 vs protobuf==3.4.0?

**Comment by wallacbe** [comment]
https://github.com/google/openhtf/pull/674

**Comment by wallacbe** [comment]
https://github.com/google/openhtf/pull/677

**Comment by wallacbe** [comment]
https://github.com/google/openhtf/pull/679

**Comment by jettisonjoe** [comment]
This was done, so marking closed.
