### ISSUE TITLE
Web GUI dosen't detect the Stations

### ISSUE THREAD

**Issue by Killerawft** [google/openhtf#715]
Hello,

I want to use the OpenHTF and tried to run the hello_world. The test produces a Json file without any error. My problem is that the Web GUI dosen't detect the station. I used the pre-build Web GUI and started it in the virtualenv with "python -m openhtf.output.web_gui". The Web GUI shows no error there is just the empy page with a blue bar on the top and the label "No stations detected.".

I run the test and Web GUI locally on my Ubuntu 16.04 LTS.

**Comment by Kenadia** [comment]
Duplicates #704 

@Killerawft Sorry for the slow work here. The old web GUI does not get a lot of attention these days. It will be supplanted by the new GUI in #720.
