### ISSUE TITLE
Add default value option to conf Declare method

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#79]
Notes from HTF meeting:
Add default option to conf Declare method
provide a default station ID

**Comment by jettisonjoe** [comment]
I see this as being particularly useful for plugs, as it seems many plugs are largely just managers of specific sets of config options. It's annoying if issue #60 can only be achieved for the most basic of tests. Having a way to specify default config values would definitely make invocations more user friendly for people coming up to speed on the usage of openhtf.

@grybmadsci, @fahhem, any strong feelings about this?

**Comment by fahhem** [comment]
I think having a default would be very useful, many configs we've used are meant
to only be overridden in case the hard-coded value stops working.

On Wed, Dec 9, 2015 at 1:40 PM, Joe Ethier < notifications@github.com > wrote:
I see this as being particularly useful for plugs, as it seems many plugs are
largely just managers of specific sets of config options. It's annoying if issue #60 can only be achieved for the most basic of tests. Having a way to specify
default config values would definitely make invocations more user friendly for
people coming up to speed on the usage of openhtf.

@grybmadsci , @fahhem , any strong feelings about this?

**Comment by grybmadsci** [comment]
pass `default_value=` to `conf.Declare()`
