### ISSUE TITLE
How can I use two of the same plug?

### ISSUE THREAD

**Issue by asuar078** [google/openhtf#842]
I need to talk to two of the same power supply for my test. I was planning on writing a plug to control the power supply but was wondering if there is a way to declare two of the same plug for a test phase. Kinda like this?

`@htf.plug(dc_sup1=DCSupply)
@htf.plug(dc_sup2=DCSupply)
def my_test(test):`

And how can I make sure that the two plugs are accessing different devices?

**Comment by arsharma1** [comment]
OpenHTF creates plugs by class, so you will need two class definitions.  This helps declare the configuration for your plugs as well.

```
class BaseDCSupply(plugs.BasePlug):
  def __init__(self):
     pass

  def get_config(self):
    raise NotImplementedError('get_config must be implemented.')

  # All implementation here...


# Subclasses only override the get_config function.
class DCSupply1(BaseDCSupply):
  def get_config(self):
    return SUPPLY_CONFIG_1


class DCSupply2(BaseDCSupply):
  def get_config(self):
    return SUPPLY_CONFIG_2


@htf.plug(dc_sup1=DCSupply1, dc_sup2=DCSupply2)
def my_test(test, dc_sup1, dc_sup2):
  pass
```
