### ISSUE TITLE
Set DEFAULT_PHASE_TIMEOUT_S to custom value

### ISSUE THREAD

**Issue by tcinbis** [google/openhtf#903]
Currently, I have a couple of tests within a PhaseGroup which in total run longer than the default phase timeout value of 180. I wonder how to change this default value which seems to be hardcoded here: https://github.com/google/openhtf/blob/bc8e5813cdf666eb6dcd7717a9d3fece73811e76/openhtf/core/phase_executor.py#L47

Is there a configuration value or parameter I can set to change it?

**Comment by JamesMTSloan** [comment]
Try using the decorator `@htf.TestPhase(timeout_s=your_timeout_s)` on your test phase function.

**Comment by tcinbis** [comment]
Thank you very much, this is exactly what I was looking for!
