### ISSUE TITLE
conf.inject_position_args doesn't support type annotations

### ISSUE THREAD

**Issue by JamesMTSloan** [google/openhtf#909]
**Python version: 3.6**

`conf.inject_positional_args` uses `inspect.getargspec()`: https://github.com/google/openhtf/blob/master/openhtf/util/conf.py#L568

In my case I am annotating the constructor for a plug and this produces an error. `inspect.getargspec()` has been deprecated with the docstring saying that `inspect.getfullargspec()` should be used instead.

Not critical by any means but should perhaps be fixed for python 3 compatibility going forward.

**Comment by tcinbis** [comment]
++ for this issue. I am experience similar problems when using annotations with Python 3.8.

**Comment by JamesMTSloan** [comment]
It looks like this is closed by #960
