### ISSUE TITLE
Device GetSerial() is returning an empty string measurement

### ISSUE THREAD

**Issue by agdeepak** [google/openhtf#93]
Using usb AdbPlug, GetSerial() call is returning empty string measurement. Expected is Device serial number string value. (This is without Cambrionix unit. Device directly connected to host machine on USB port).

@openhtf.TestPhase(timeout_s=360)
@plug(adb=usb.AdbPlug)
@measures(Measurement('Serialnum'))
def DeviceSerialNum(test, adb):
    print (type(adb.GetSerial()))
    test.measurements.Serialnum = adb.GetSerial()
    print 'getserial done'

**Comment by jettisonjoe** [comment]
Let's hold off on working on ADB until we decide if we're going to replace it with mobly's implementation.
