### ISSUE TITLE
guzzle_pb2.COMPRESSED_MFG_EVENT does not exist

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#945]
https://github.com/google/openhtf/blob/master/openhtf/output/callbacks/mfg_inspector.py

guzzle_pb2.COMPRESSED_MFG_EVENT does not exist

Should this be COMPRESSED_TEST_RUN ?

enum PayloadType {
  COMPRESSED_TEST_RUN = 1;
  COMPRESSED_VARZ = 2;
  COMPRESSED_LOGFILE = 3;
}

**Comment by arsharma1** [comment]
Looks like it.  Please send me a pull request.

**Comment by wallacbe** [comment]
https://github.com/google/openhtf/pull/946/commits/f9de10231d2970c9177ddaf4e8a8b3ae65c61403

**Comment by arsharma1** [comment]
Merged in.  Thanks!
