### ISSUE TITLE
2.0 Release tag?

### ISSUE THREAD

**Issue by lalten** [google/openhtf#967]
Hi @Kenadia and @arsharma1 ,
Lots of good stuff has been added to OpenHTF since the last release (1.3.0, May 2018) and tag (1.4.4, Oct 2019).

It would be awesome if you could do a 2.0 release!
https://github.com/google/openhtf/blob/70550f99640c2dd6b0f87e2e3013c5a5c5f9f350/CHANGELOG#L1

**Comment by arsharma1** [comment]
I will try to get a 2.0 release out in the next month or so.

**Comment by mrobak-cpi** [comment]
Is there any chance of 2.0 going out soon?

**Comment by alexagv** [comment]
Any updates on this? @arsharma1

**Comment by glados-verma** [comment]
Just did a 1.5 release.
