### ISSUE TITLE
Need Advice on how to Architect a Test Plan

### ISSUE THREAD

**Issue by sbluatx** [google/openhtf#979]
Folks, i have a question on how to architect a test plan for the following scenario:

**[trigger]** ->
-> **[set of tests]** ->Pass/Fail->**[if Pass Do A, else Do B. if ABORT Stop, else loop back]**
                           ^------------------------------------------------------------------'
I have a a set of phases i need to run that would collectively in the box called **[set of tests]**, then based on the results, i have another test node that does something specific, indicated by **[if Pass Do A, Else Do B...]**; then I go back to running **[set of tests]** then continue repeating the cycle (infinitely) between the two nodes, until I determine that i need to abort, in which case i abort out.

Can you please advice me on how I can setup such a scenario using openhtf?

**Comment by cloudguruab** [comment]
I would like to contribute what would be a great place to start @sbluatx

**Comment by sbluatx** [comment]
This was directed to the folks that developed the tool.  i'm wondering if this tool already supports the indicated scenario

**Comment by cloudguruab** [comment]
@sbluatx no worries! I wouldn't mind giving it a try from what I can find on the docs & a few other sources.

**Comment by glados-verma** [comment]
I haven't used them myself, but PhaseBranches are supposed to do what you've described.
