### ISSUE TITLE
I'd like to help out on this project. How would I go about doing this? 

### ISSUE THREAD

**Issue by DanWhitney** [google/openhtf#988]
I've been following this project for a while. 
I'm new to python and in the process of learning.
I'd like to better understand how this projects works. 
I've read all of the .md files, but am now wondering where to go from here
Is there a good place to continue?

**Comment by jettisonjoe** [comment]
The all_the_things.py example test is a good place to start if you haven't looked at it already. Also, many of the modules have fairly detailed docstrings. I recommend looking at some of the docstrings in core/ as a jumping-off point!

**Comment by glados-verma** [comment]
Closing this, please reopen if you still have questions.
