### ISSUE TITLE
Bumping pyOpenSSL and other requirements.

### ISSUE THREAD

**Issue by ablatner** [google/openhtf#993]
pyOpenSSL is pinned to a version from 2017 (Latest 17.X). Is safe to bump this to a more recent version? Due to https://github.com/pyca/pyopenssl/issues/973, this version is incompatible with versions of [cryptography](https://github.com/pyca/cryptography) more recent than 3.2.1 in October 2020. This could lead to security vulnerabilities in venvs that use openhtf.

The pyOpenSSL constraint has not been updated since 2017 so, it seems like the constraint was simply "pin to current major version" rather than a technical constraint.

**Comment by dbhatman** [comment]
Fixed as of #1022
